# Generated by Django 3.2.9 on 2021-11-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_rename_cp_product_sp'),
        ('Customer', '0002_remove_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='productKey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productKey', to='bakery.product'),
        ),
    ]
