# Generated by Django 3.2.9 on 2021-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ManyToManyField(to='bakery.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
