# Generated by Django 3.2.9 on 2021-11-02 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20211102_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
