# Generated by Django 3.2.9 on 2021-11-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_product_cp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CP',
            new_name='SP',
        ),
    ]
